### ISSUE TITLE
Azure App Service

### ISSUE THREAD

**Issue by herenickname** [adonisjs/adonis-websocket#3]
Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
at e (D:\home\site\wwwroot\node_modules\uws\uws.js:31:19)
at Object.<anonymous> (D:\home\site\wwwroot\node_modules\uws\uws.js:35:3)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Ws.attach (D:\home\site\wwwroot\node_modules\adonis-websocket\src\Ws\index.js:99:23)
2017-01-28T13:12:39 Startup Request, url: /, method: GET, type: request, pid: 9140,4,19, ScmType: None

**Comment by thetutlage** [comment]
Sorry it took a while
