### ISSUE TITLE
Cant emit/broadcast on dynamic topic

### ISSUE THREAD

**Issue by mbcausing** [adonisjs/adonis-websocket#64]
Im trying to emit on dynamic topic on certain channel but i cant make it work
this is the code that i use to test if i can get the channel object

i already tried this
``` node
const Ws = use('Ws')

class LocationController {
  constructor ({ socket, request, auth }) {
      this.socket = socket
      this.request = request
      this.auth = auth
  }

  async onNewLocation(data){
       const userId = 1234
        Ws.getChannel(`d:${userId}`).topic(`d:${userId}`).broadcast('sample')
  }
}

module.exports = LocationController
```
and this
``` node
const Ws = use('Ws')

class LocationController {
  constructor ({ socket, request, auth }) {
      this.socket = socket
      this.request = request
      this.auth = auth
  }

  async onNewLocation(data){
        const userId = 1234
        Ws.getChannel(`d`).topic(userId).broadcast('sample')
  }
}

module.exports = LocationController
```

and this is the code in client
```node
import Ws from '@adonisjs/websocket-client'
export class AppComponent {
  title = 'app';


    constructor(){
        const ws = Ws('ws://localhost:3333', {
            path: 'websocket'
        })
        ws.connect()


        ws.on('open', () => {
            this.locationChannel(ws)
        })

    }

    locationChannel = (_ws) => {
        const userId = 1234
        const location = _ws.subscribe(`d:${userId}`)
        location.on('ready', () => {
            location.emit('newLocation', {latlng: '33.3632256, -117.0874871'})
        })

    }
}
```
and this is the error
```                                  ^
TypeError: Cannot read property 'topic' of undefined
   at Channel.Ws.channel [as _onConnect] (/home/**/Code/adonis/**/start/socket.js:11:35)
    at process.nextTick (/home/**/Code/adonis/**-api/node_modules/@adonisjs/websocket/src/Channel/index.js:177:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by thetutlage** [comment]
Try it as follows

```js
Ws.getChannel('d:*').topic(`d:${userId}`)
```

**Comment by mbcausing** [comment]
I tried that and now its working
Thanks for the immediate reply @thetutlage
